'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>Number(x).toLocaleString('en-IN'), pct=x=>(100*Number(x)).toFixed(1)+'%';
let regional=[],allCases=[],lastResult=null;
async function api(path,options){const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function stat(value,label){return `<div class="stat"><b>${esc(value)}</b><span>${esc(label)}</span></div>`;}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==b.dataset.view);document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('active',n===b));}));
function drawRegional(){const key=$('sort').value;const rows=[...regional].sort((a,b)=>key==='state_ut'?a[key].localeCompare(b[key]):Number(b[key])-Number(a[key]));$('regionalRows').innerHTML=rows.map(r=>`<tr><td>${esc(r.state_ut)}</td><td>${num(r.cases_2021)}</td><td>${num(r.cases_2022)}</td><td><b>${num(r.cases_2023)}</b></td><td>${r.growth_pct===''?'N/A':Number(r.growth_pct).toFixed(1)+'%'}</td><td><span class="bar" style="width:${Number(r.national_share_2023_pct)*3}px"></span>${Number(r.national_share_2023_pct).toFixed(2)}%</td></tr>`).join('');}
$('sort').addEventListener('change',drawRegional);
function filterCases(){const city=$('city').value,q=$('search').value.toLowerCase();const rows=allCases.filter(c=>(!city||c.city===city)&&(!q||(c.case_id+' '+c.narrative).toLowerCase().includes(q))).sort((a,b)=>b.incident_start.localeCompare(a.incident_start));$('query').innerHTML=rows.map(c=>`<option value="${esc(c.case_id)}">${esc(c.case_id)} · ${esc(c.city)}</option>`).join('');if(rows.length)$('query').selectedIndex=0;$('rank').disabled=!rows.length;}
$('city').addEventListener('change',filterCases);$('search').addEventListener('input',filterCases);
function showResult(data){lastResult=data;const q=data.query;$('queryDetail').innerHTML=`<h2>${esc(q.case_id)} <span class="tag">${esc(q.data_kind||'imported / unverified')}</span></h2><div class="querygrid"><div><span>Place</span>${esc(q.city)}, ${esc(q.state_ut)}</div><div><span>Occurrence</span>${esc(q.incident_start)}</div><div><span>Crime family</span>${esc(q.crime_family)}</div><div><span>Language</span>${esc(q.language||'not supplied')}</div></div><p class="narrative">${esc(q.narrative)}</p>`;
$('results').innerHTML=data.results.length?data.results.map((r,i)=>`<details class="result"><summary><div><b>${i+1}. ${esc(r.case_id)}</b><small>${esc(r.city)} · ${r.distance_km} km · ${r.gap_days} days · MO coverage ${pct(r.mo_coverage)}</small></div><strong>${r.score.toFixed(3)}<small>demo score</small></strong></summary>${r.low_evidence?'<p class="notice">Low observed MO coverage. Interpret cautiously.</p>':''}<table><thead><tr><th>Factor</th><th>Value</th><th>Logit contribution</th></tr></thead><tbody>${r.factors.map(f=>`<tr><td>${esc(f.feature)}</td><td>${f.value.toFixed(3)}</td><td>${f.logit_contribution.toFixed(3)}</td></tr>`).join('')}</tbody></table></details>`).join(''):'<p>No earlier eligible cases. Select a later query.</p>';$('export').disabled=false;status(data.notice);}
$('rank').addEventListener('click',async()=>{try{$('rank').disabled=true;status('Ranking historical candidates…');showResult(await api('/api/link?case_id='+encodeURIComponent($('query').value)+'&limit=20'));}catch(e){status(e.message,true);}finally{$('rank').disabled=false;}});
$('export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(lastResult,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ihstmo-ranking.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('analyze').addEventListener('click',async()=>{try{const file=$('upload').files[0];if(!file)throw Error('Choose a CSV file first.');if(file.size>1900000)throw Error('CSV must be smaller than 1.9 MB.');$('analyze').disabled=true;status('Validating CSV and ranking in memory…');showResult(await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv:await file.text(),query_id:$('uploadQuery').value.trim()})}));}catch(e){status(e.message,true);}finally{$('analyze').disabled=false;}});
async function init(){try{const [r,c,e,m]=await Promise.all(['/api/regional','/api/cases','/api/evaluation','/api/manifest'].map(p=>api(p)));regional=r.rows;allCases=c.cases;drawRegional();const totals=[2021,2022,2023].map(y=>regional.reduce((s,r)=>s+Number(r['cases_'+y]),0));$('regionalStats').innerHTML=totals.map((t,i)=>stat(num(t),(2021+i)+' registered cases')).join('')+stat(pct(totals[2]/totals[1]-1),'2022 → 2023 national change');$('city').innerHTML+=[...c.cities].map(n=>`<option>${esc(n)}</option>`).join('');filterCases();$('evalStats').innerHTML=stat(e.pair_metrics.roc_auc.toFixed(3),'Synthetic test ROC AUC')+stat(e.pair_metrics.average_precision.toFixed(3),'Synthetic average precision')+stat(pct(e.ranking.recall_at_10),'Synthetic end-to-end Recall@10')+stat(e.offender_overlap,'Offenders shared across splits');$('ablations').innerHTML=e.ablations.map(a=>`<tr><td>${esc(a.model)}</td><td>${a.roc_auc.toFixed(3)}</td><td>${a.average_precision.toFixed(3)}</td></tr>`).join('');$('protocol').innerHTML=`<p>${Object.entries(e.splits).map(([s,v])=>`<b>${esc(s)}</b>: ${v.cases} cases / ${v.offenders} generated offenders`).join('<br>')}</p><p>Historical ranking: ${e.ranking.eligible_queries} eligible queries; ${e.ranking.excluded_no_historical_partner} without earlier partners excluded from recall.</p><p>Candidate recall: ${pct(e.ranking.candidate_recall)}<br>MRR: ${e.ranking.mrr.toFixed(3)}<br>Pair Brier score: ${e.pair_metrics.brier.toFixed(4)}<br>Positive-pair prevalence: ${pct(e.pair_metrics.prevalence)}</p><p class="note">${e.limitations.map(esc).join(' ')}</p>`;$('datasetCards').innerHTML=m.files.map(f=>`<article class="dataset"><span class="tag">${esc(f.kind)}</span><h2>${esc(f.file)}</h2><p>${num(f.rows)} rows · ${f.columns.length} columns</p><p class="note">SHA-256: ${esc(f.sha256.slice(0,24))}…</p><a href="/download/${encodeURIComponent(f.file)}" download>Download CSV ↗</a></article>`).join('');status('Ready · official totals reconciled · synthetic experiments labelled');}catch(e){status('Unable to load workspace: '+e.message,true);}}
init();
